config/routes.rb
Rails.application.routes.draw do
  root to: 'teams#index'
  resources :games
  resources :teams do
    resources :players
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :teams
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :team
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :players, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
    render :index
  end

  def new
    @game = Game.new
    render :new
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      redirect_to game_path(@game)
    else
    render :new
    end
  end

  def show
    @games = Game.all
  end

  private
  def game_params
    params.require(:game).permit(:team_one, :team_two)
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def new
    @team = Team.find(params[:team_id])
    @player = @team.players.new
    render :new
  end

  def create
    @team = Team.find(params[:team_id])
    @player = @team.players.new(player_params)
    if @player.save
      redirect_to team_path(@team)
    else
    render :new
    end
  end

  def show
    @team = Team.find(params[:team_id])
    @player = Player.find(params[:id])
    render :show
  end

  def edit
    @team = Team.find(params[:team_id])
    @player = Player.find(params[:id])
    render :edit
  end

  def update
    @player = Player.find(params[:id])
    if @player.update(player_params)
      redirect_to team_path(@player.team)
    else
      render :edit
    end
  end

  def destroy
    @player = Player.find(params[:id])
    @player.destroy
    redirect_to team_path(@player.team)
  end

  private
    def player_params
      params.require(:player).permit(:name)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  def index
    @teams = Team.all
    render :index
    # Code for listing all teams goes here.
  end

  def new
    @team = Team.new
    render :new
    # Code for new team form goes here.
  end

  def create
    @team = Team.new(team_params)
    if @team.save
      redirect_to teams_path
    else
      render :new
    end
    # Code for creating a new team goes here.
  end

  def edit
    @team = Team.find(params[:id])
    render :edit
    # Code for edit team form goes here.
  end

  def show
    @team = Team.find(params[:id])
    render :show
    # Code for showing a single team goes here.
  end

  def update
    @team = Team.find(params[:id])
    if @team.update(team_params)
      redirect_to teams_path
    else
      render :edit
    end
    # Code for updating an team goes here.
  end

  def destroy
    @team = Team.find(params[:id])
    @team.destroy
    redirect_to teams_path
    # Code for deleting an team goes here.
  end

  private
    def team_params
      params.require(:team).permit(:name, :coordinator)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/index.html.erb
<h1>Games</h1>

<% if @games.any? %>
  <p>Definitely some games</p>
  <ul>
  <% @games.each do |game| %>
    <li><%= game.team_one %> vs <%= game.team_two %></li>
  <% end %>
  </ul>
<% else %>
  <p>No games at this time.</p>
<% end %>

<p><%= link_to "New Game", new_game_path %></p>

app/views/games/new.html.erb
<h1>Add a new game:</h1>

<%= form_for [@game] do |f| %>
  <%= f.label :team_one %>
  <%= f.text_field :team_one %>
  <p>VERUS</p>
  <%= f.label :team_two %>
  <%= f.text_field :team_two %>
  <p><%= f.submit %></p>
<% end %>

app/views/games/show.html.erb
<h1>Games</h1>

<% if @games.any? %>

  <% @games.each do |game| %>
    <!-- insert logic later -->
  <% end %>
<% else %>
  <p>No games at this time.</p>
<% end %>

<p><%= link_to "New Game", new_game_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UltraTeamLeague</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/edit.html.erb
<h1>Edit player:</h1>

<%= form_for [@team, @player] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <p><%= f.submit %></p>
<% end %>

app/views/players/new.html.erb
<h1>Add a new player:</h1>

<%= form_for [@team, @player] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <p><%= f.submit %></p>
<% end %>

app/views/players/show.html.erb
<h1>Player: <%= @player.name %></h1>
<h2>Team: <%= @team.name %></h2>

<p><%= link_to "Edit player", edit_team_player_path(@team, @player) %></p>
<p><%= link_to "Delete player", team_player_path(@team, @player),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to team", team_path(@team) %></p>